server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;

  location /health {
    proxy_pass ${SERVER_SCHEME}://${SERVER_HOST}:${SERVER_PORT};
    proxy_ssl_server_name on;
    proxy_ssl_name ${SERVER_HOST};
    proxy_http_version 1.1;
    proxy_set_header Host ${SERVER_HOST};
  }

  location /socket.io/ {
    proxy_pass ${SERVER_SCHEME}://${SERVER_HOST}:${SERVER_PORT};
    proxy_ssl_server_name on;
    proxy_ssl_name ${SERVER_HOST};
    proxy_http_version 1.1;
    proxy_set_header Upgrade ${DOLLAR}http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host ${SERVER_HOST};
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
