services:
  - type: web
    name: crdt-editor-server
    runtime: docker
    dockerfilePath: ./server/Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: crdt-editor-db
          property: connectionString
      - key: PORT
        value: '3000'

  - type: web
    name: crdt-editor-client
    runtime: docker
    dockerfilePath: ./client/Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: DOLLAR
        value: '$'
      - key: SERVER_HOST
        fromService:
          type: web
          name: crdt-editor-server
          envVarKey: RENDER_EXTERNAL_HOSTNAME
      - key: SERVER_SCHEME
        value: https
      - key: SERVER_PORT
        value: '443'

databases:
  - name: crdt-editor-db
    plan: free
    databaseName: crdt_editor
    user: crdt
